### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NoFeedRoot)'

### ISSUE THREAD

**Issue by whoizit** [jahzielv/hemingway#17]
```
~ > cargo install hemingway
~ > hem add https://rsshub.app/twitter/user/msvetov
~ > hem
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NoFeedRoot)', /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/hemingway-0.7.1/src/lib.rs:221:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by whoizit** [comment]
```
~ > RUST_BACKTRACE=1 hem                                                                                                
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NoFeedRoot)', /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/hemingway-0.7.1/src/lib.rs:221:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/result.rs:1355:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: futures_util::stream::stream::StreamExt::poll_next_unpin
   5: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::runtime::enter::Enter::block_on
   8: tokio::runtime::context::enter
   9: tokio::runtime::handle::Handle::enter
  10: hem::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by whoizit** [comment]
with updated dependencies (cargo install cargo-edit; cargo upgrade)
```
~/build/hemingway > rustc -V
rustc 1.54.0-nightly (e4a603270 2021-06-07)
~/build/hemingway > RUST_BACKTRACE=1 ./target/debug/hem
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(NoFeedRoot)', /home/user/build/hemingway/src/lib.rs:221:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/result.rs:1037:23
   4: hemlib::read_feed_fast_duration::{{closure}}::{{closure}}::{{closure}}
             at ./src/lib.rs:221:36
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/future/mod.rs:80:19
   6: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/futures_unordered/mod.rs:521:17
   7: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/mod.rs:1416:9
   8: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/buffer_unordered.rs:79:15
   9: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/stream/stream/collect.rs:50:26
  10: hemlib::read_feed_fast_duration::{{closure}}
             at ./src/lib.rs:272:5
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/future/mod.rs:80:19
  12: hem::main::{{closure}}
             at ./src/main.rs:41:29
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/future/mod.rs:80:19
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:106:9
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/thread/local.rs:400:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/std/src/thread/local.rs:376:9
  18: tokio::coop::with_budget
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:99:5
  19: tokio::coop::budget
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/coop.rs:76:5
  20: tokio::park::thread::CachedParkThread::block_on
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/enter.rs:151:13
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/thread_pool/mod.rs:71:9
  23: tokio::runtime::Runtime::block_on
             at /home/user/.asdf/installs/rust/nightly/registry/src/github.com-1ecc6299db9ec823/tokio-1.6.1/src/runtime/mod.rs:452:43
  24: hem::main
             at ./src/main.rs:71:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/e4a60327063e82413eed50a10df3b7d19b77bda0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by whoizit** [comment]
```
~/build/hemingway > hem list
https://rsshub.app/twitter/user/msvetov
https://rsshub.app/twitter/user/civ_soc
https://rsshub.app/twitter/user/fbkinfo
https://rsshub.app/twitter/user/navalny
```

**Comment by jahzielv** [comment]
Thanks for the feedback and the detailed logs! I see that this project is gaining at least a little bit of interest so I'll do my best to take some time over the next few days to work on these bugs!
